.TH "DNSPING" 1 "2020"
.SH NAME
dnsping \- check packet loss and latency issues with DNS servers
.SH SYNOPSIS
\fBfortio\fP [flags] \fIquery\fP \fIdns-server\fP
.SH DESCRIPTION
\fIquery\fP is the query (typically hostname) to be resolved 
repeatedly by \fBdns-server\fP.
.SH "SEE ALSO"
\fBdnsping -h\fP for all the flags and https://fortio.org/ for more
documentation.
