# Concatenated after ../Dockerfile to create the tgz
FROM docker.io/fortio/fortio.build:v40 as stage
WORKDIR /stage
COPY --from=release /usr/bin/dnsping usr/bin/dnsping
COPY dnsping.1 usr/share/man/man1/dnsping.1
RUN mkdir /tgz
# Make sure the list here is both minimal and complete
# we could take all of * but that adds system directories to the tar
RUN tar cvf - usr/share/man/man1/dnsping.1 usr/bin/dnsping | gzip --best > /tgz/dnsping-linux_x64-$(./usr/bin/dnsping -v).tgz
COPY --from=build /out/dnsping.exe /tmp
COPY --from=build /out/dnsping.mac /tmp/dnsping
WORKDIR /tmp
RUN zip -9  -r dnsping_win_$(/stage/usr/bin/dnsping -v).zip dnsping.exe && mv *.zip /tgz
RUN zip -9  -r dnsping_mac_$(/stage/usr/bin/dnsping -v).zip dnsping && mv *.zip /tgz
WORKDIR /tgz
FROM scratch
COPY --from=stage /tgz/ /tgz/
