name: "Code Coverage"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-go@v4
      with:
          go-version: '1.20'
          check-latest: true
    - name: Run test coverage
      run: go test -race -coverprofile=coverage.out -covermode=atomic
    - uses: codecov/codecov-action@v3
      with:
        files: coverage.out
